# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/peddection',
                'doc_host': 'https://abyszero-org.github.io',
                'git_url': 'https://github.com/abyszero-org/peddection',
                'lib_path': 'peddection'},
  'syms': { 'peddection.core': {'peddection.core.foo': ('core.html#foo', 'peddection/core.py')},
            'peddection.kitti.data': {},
            'peddection.kitti.vis': { 'peddection.kitti.vis.loadVeloAsPcd': ('kitti_explore.html#loadveloaspcd', 'peddection/kitti/vis.py'),
                                      'peddection.kitti.vis.plotCloud': ('kitti_explore.html#plotcloud', 'peddection/kitti/vis.py')}}}
