# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_kitti_dl.ipynb.

# %% auto 0
__all__ = ['KITTI_ROOT']

# %% ../../nbs/02_kitti_dl.ipynb 3
from typing import Union
from pathlib import Path
from os import PathLike, environ

from pathlib import Path
import numpy as np
import open3d as o3d

import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
import plotly.graph_objects as go

import torch
import torchvision
from torch.utils.data import DataLoader


# %% ../../nbs/02_kitti_dl.ipynb 4
KITTI_ROOT = environ.get("KITTI_ROOT", Path("/media/usbhd4tb/datasets/kitti"))
